### ISSUE TITLE
How to get OneDriveUser State.json file

### ISSUE THREAD

**Issue by duykhongphai** [andy-miles/onedrive-java-sdk#1]
How to get OneDriveUser State.json file

**Comment by andy-miles** [comment]
Assuming you're using either one of the provided SingleUser*AuthInfoStore implementations (i.e., the default), it's a file path that **you specify yourself in your application**.  Upon successful user oauth grants, the store will persist the access tokens to this file so that the next time your application runs, you don't have to request oauth grants to the user again.
